[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
script = 'forge-script'
test = 'forge-test'
cache_path  = 'cache_forge'
fs_permissions = [{ access = "read", path = "./"}]

solc = "0.8.21"
optimizer = true
optimizer_runs = 200